# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fb34c818cf07e2ca0ff31562fb46499b01da423e1ccacde4d00ba71c5dc843c256171c62a0f04a95161aafc7c296668b690cb117cfc8b16efb3c25d29afe080

test:
  secret_key_base: 0fb34c818cf07e2ca0ff31562fb46499b01da423e1ccacde4d00ba71c5dc843c256171c62a0f04a95161aafc7c296668b690cb117cfc8b16efb3c25d29afe080

staging:
  secret_key_base: 0fb34c818cf07e2ca0ff31562fb46499b01da423e1ccacde4d00ba71c5dc843c256171c62a0f04a95161aafc7c296668b690cb117cfc8b16efb3c25d29afe080
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
